# Generated by Django 5.1 on 2024-09-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='emp_id',
            new_name='testimonial',
        ),
    ]
